services:
  # Servicio de la Aplicación PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production # Especifica que se debe construir la etapa final 'production'
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  # Servidor Web Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8070:8070"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network

  # Servicio de Redis
  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  redis-data:
    driver: local