services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      APP_ENV: production
      APP_DEBUG: false
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
    volumes:
      - .:/var/www
    ports:
      - "8069:9000"  # Exposed for Cloudflare tunnel
    networks:
      - laravel-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  redis-data:
    driver: local